### ISSUE TITLE
Socket io being used?

### ISSUE THREAD

**Issue by Jbarget** [koalabears/koala-shoes#18]
"so"??

**Comment by jackcarlisle** [comment]
No it's not being used, we set it up because we were planning on using it for our real time updates for the issues but we didn't get that far! @Jbarget

**Comment by Jbarget** [comment]
gotcha, you gonna get the realtime updates going or delete the file?

**Comment by jackcarlisle** [comment]
going to delete the file @Jbarget

**Comment by jackcarlisle** [comment]
it's been removed! @Jbarget
