### ISSUE TITLE
githubapi.js

### ISSUE THREAD

**Issue by hdrdavies** [koalabears/koala-shoes#21]
Nice exporting :+1: 

Also nice use of the parseBody function!

When you're refactoring, you might want to clean up the console.logs

https://github.com/koalabears/koala-shoes/blob/master/githubApi.js#L12
https://github.com/koalabears/koala-shoes/blob/master/githubApi.js#L15
https://github.com/koalabears/koala-shoes/blob/master/githubApi.js#L17
https://github.com/koalabears/koala-shoes/blob/master/githubApi.js#L29

**Comment by jackcarlisle** [comment]
all cleaned up! @hdrdavies
